### ISSUE TITLE
Doesn't seem to support 3.9 and below

### ISSUE THREAD

**Issue by Coler6** [CNDRD/siegeapi#1]
The unions do not work for 3.9. You use `Union[str, int]` for 3.9 and below.

**Comment by CNDRD** [comment]
Thanks for this! Since I'm working on this on the 3.10 it didn't occur to me to think about the fact that typings have changed..
I have just fixed the typings for both Python 3.8 and 3.9 in the [guns](https://github.com/CNDRD/siegeapi/tree/guns) branch

I am waiting on merging this branch until the new season drops (should be in a week) if maybe Ubi doesn't wanna surprise us with some fixes to the API.
If not, there will have to be some more work done on that which would mean breaking changes maybe so I'm holding off on that
