### ISSUE TITLE
"bug" in player.max_mmr

### ISSUE THREAD

**Issue by Xample33** [CNDRD/siegeapi#10]
Suppose having this function:
```python
async def test():
    auth = Auth('email', 'password')
    player = await auth.get_player(name='xxx')
    ranked = await player.load_ranked()
    
    print(f'max mmr: {ranked.max_mmr}')
    # max_mmr: -1
    await auth.close()
```
and the player has played only one ranked game in current season, the value of `ranked.max_mmr` is `-1`
i think that this is not supposed to be `-1` but at most `0` because with one single match, the mmr cannot be calculated.

**Comment by CNDRD** [comment]
That's a weird thing..
Since that's only supposed to happen when Ubi doesn't return the previous rank mmr and the next rank mmr (basically any case, other than ranked..)
https://github.com/CNDRD/siegeapi/blob/280784140d53c2ddcca21d2f89dd982290cc1b69/siegeapi/ranks.py#L54-L57

Ubisofts API is so stupid it could very well be a one-off case
But, I personally, am using this library daily to grab data for ~10 users every 30 minutes
Never seen that happen

So if you could provide me with the account name you're using so I could investigate further
(Or any other that has only one game played; I ain't searching for one)

_(I also don't know why I decided to return `-1` and not `0`, imma fix that in the next release probably)_

**Comment by Xample33** [comment]
Maybe you can just set the return to `0` instead of `-1`.
But the username is `Xampl3_` (mine), and i have played only one ranked game in this season.

**Comment by CNDRD** [comment]
I can definitely do that, that isn't a problem
This just isn't supposed to happen when you want ranked stats...

**Comment by Xample33** [comment]
yeah yeah

**Comment by CNDRD** [comment]
I have pushed the updated code that correctly returns `0` when calling `.load_ranked()`
Along with a new **v4.1.5** release on [GitHub releases](https://github.com/CNDRD/siegeapi/releases/tag/v4.1.5) & [PyPI](https://pypi.org/project/siegeapi/4.1.5/)

This definitely wasn't happening in the past so thanks for letting me know
