### ISSUE TITLE
Return of player.total_time_played

### ISSUE THREAD

**Issue by Xample33** [CNDRD/siegeapi#11]
What is the return of `player.total_time_played`?
I don't think is in seconds, so what?

**Comment by CNDRD** [comment]
It is most definitely in seconds

Don't know about the math if you were to add `.pvp_time_played` and `.pve_time_played` because we're talking about Ubisoft here

But from my testing it is in seconds
And you can check that on my account _(CNDRD on both Ubi and Steam)_,
where I have `2,318 hours` on Steam and `2017h 50m 59s` or `7,264,259 seconds` I get straight from Ubi,
_Difference being the fact that Steam counts the time the .exe is running and Ubi tracking the actual in-game time_

You also cannot really check this anywhere other than, probably, their website and their overlay since any stat tracker that I've checked is displaying the data that got frozen all the way back in Y6S4..
_(That is very probably because Ubisoft has explicitly forbidden them from using this.. Or so I'm told by my sources)_

P.S.: It is also possible that if the times you're getting back from them look sus, Ubi just fucked up, as they always do
