### ISSUE TITLE
Support for Y7S4?

### ISSUE THREAD

**Issue by maxoyed** [CNDRD/siegeapi#12]
Thx for your amazing siegeapi! I have checked the commit history, seems like that some work for Y7S4 is ongoing, but I've tried the latest version, Y7S4 stats seems unavailable currently.

**Comment by CNDRD** [comment]
Thanks :D
So far i'm quite swamped with my actual work stuff, and also with the fact that they changed the stuff up a bit and I'm trying to figure out the best way to do this..

Also it's not known how to access the new "MMR" or whatever since its not present on the official tracker (despite the tracker sites having it...)

As a side note, I've just sat down to properly analyze the new endpoints and shit as I got the notification for this issue 😄

**Comment by CNDRD** [comment]
v5.0.0 is now out on [GitHub](https://github.com/CNDRD/siegeapi/releases/tag/v5.0.0) and [PyPI](https://pypi.org/project/siegeapi/5.0.0/)

**Comment by maxoyed** [comment]
They hide MMR from Y7S4, only RP(Ranked Point) is visible now.

**Comment by CNDRD** [comment]
I know that's how it works in-game
But where it is in the API, that's a whole different story

**Comment by maxoyed** [comment]
Maybe it's also hide from the API?

**Comment by CNDRD** [comment]
Quite possible, however the trackers have that info and I doubt they are relying only on somehow having data from their Overwolf overlays.. Unlike them though me and the other devs had to figure stuff out on our own, but that's a whole different story..
So until someone shares a way on GitHub or I find it, we will have no "Ranked Points"

official tracker - no rank related data whatsoever - the moment you switch on the "Crossplay stats" instead of "Historical stats" you get nothing (the website looks like it wants to get something for the new season but the API returns nothing)
TRN - they have it
tabstats - same as TRN (they show *"Real MMR"*, which is pretty misleading..)
r6stats.com - looks like they died in Crystal Guard..
r6db.net - no data past Y7S4 at all
