### ISSUE TITLE
Can I get past ranks?

### ISSUE THREAD

**Issue by Lejvnx** [CNDRD/siegeapi#17]
Is it possible to get rank information for past seasons using `load_ranked_v2()`?
If I can't do it, is there any other way to get it?
(I would like to get rank on Y7S4 and Y8S1.)

**Comment by CNDRD** [comment]
You can get these by `player.load_summaries()`
You can even limit this call by doing `player.load_summaries(seasons=['Y7S4', 'Y8S1'])` so you'll only get the data you want

**Comment by Lejvnx** [comment]
Thanks for replying to me.
 I tried that method as well, but it didn't give me the information I wanted, I could get the information for the `Summary` class, but not for the `Rank` class.
I want to get the `rank_id` or `rank` of Y7S4 and Y8S1.


PS.
`player.load_summaries()` does not have a `seasons` argument.
So I get the following error
`TypeError: Player.load_summaries() got an unexpected keyword argument 'seasons'`
https://github.com/CNDRD/siegeapi/blob/8a95be50509cd8f7c7dae35659c8047149f7f977/siegeapi/player.py#L134

**Comment by CNDRD** [comment]
Sorry, you're right, got it messed up 😄 (it was there though.. https://github.com/CNDRD/siegeapi/commit/adc4c811a0e238c6e9f4a8dd86779767fdccf9a7)

I got my things messed up, sorry..

Ubi only keeps the stats for _120 days_
There is no way of getting such data from before that, only way to get that is to cache these stats on your own (Which is top tier stupid.)

Only way i can think of is looking at the users' inventory and seeing the highest charm in there lmao
(Also incredibly stupid, since you get the charm for the first rank in the category - gold for gold 5..)

I would love to help you, unfortunately, short of using a third party API (and there aren't any 😞), there is nothing we can do

**Comment by Lejvnx** [comment]
Thanks for working on a solution.
