### ISSUE TITLE
load_all_operators docs mistake

### ISSUE THREAD

**Issue by Coler6** [CNDRD/siegeapi#2]
load_all_operators is displayed as load_operators in the docs.

**Comment by CNDRD** [comment]
That is actually correct. `load_all_operators()` is for versions 1.x.x while `load_operators()` is for versions 2.x.x.
I admit that putting that into the docs while the version is not _fully_ out (but on [another branch](https://github.com/CNDRD/siegeapi/tree/guns) and on [pypi](https://pypi.org/project/siegeapi/#history) as a pre-release), I've done the docs a while back and since v2 is public I've felt like having the docs for it is a good thing
