### ISSUE TITLE
Anyway to search a user, using their previous name?

### ISSUE THREAD

**Issue by Newcoolboys** [CNDRD/siegeapi#24]
Is it possible to search a user using their previous name using this api?

**Comment by Ken-Miles** [comment]
Not that I know of. IIRC the Ubisoft API doesn't provide anybody's old usernames so the only way to do this would be to track it yourself or find another service that tracks usernames or smth

**Comment by CNDRD** [comment]
Exactly, as @Ken-Miles said, no way to search by old usernames.
You can either track it yourself or use [TRN](https://r6.tracker.network/) since nobody else does that really (but that has its own drawbacks like no API, and their own problems with showing incorrect stats and stuff like that, but the names should be alright lmao).
