### ISSUE TITLE
Quick question: does load general return quick match stats as well?

### ISSUE THREAD

**Issue by Coler6** [CNDRD/siegeapi#3]
I'm somewhat new to the game and the api works fine but when I tried loading general stats everything is 0. I also tried it with a friend and his returns a bunch of info. Is this because it only returns unranked stats and is there a method to return quick match stats?

**Comment by CNDRD** [comment]
The problem with general stats is that Ubisoft stopped updating the data on the endpoint that `load_general()` uses at the start of operation High Calibre (came out 2021-11-30), that's why youre seeing 0 on everything if you're new to the game.

This has been reported on [R6FIX](https://r6fix.ubi.com/projects/RAINBOW6-SIEGE-LIVE/issues/LIVE-35064), but I don't really believe that they will fix it, I think it's intentional.

That is also why I'm holding off on releasing siegeapi 2.0 since I'll need to probably rework the whole thing once again to support new endpoints.

Also, if you have any further questions like this, I don't have problem with them, but reaching to me out on Discord (CNDRD#2233) would be much better, not to mention quicker 😃

**Comment by Coler6** [comment]
Ah ok, thank you!
