### ISSUE TITLE
seems to be no way to find the all time highest rank over a players career

### ISSUE THREAD

**Issue by ghost** [CNDRD/siegeapi#30]
it seems to me that there is no apparent way to get max rank for previous seasons.

**Comment by CNDRD** [comment]
What "previous seasons" exactly are you talking about?

**Comment by ghost** [comment]
It seems to me (I could be wrong this is the first time using an api lol), that the max rank function only gets the max rank for the current season. I would like if it could get the all time highest rank of the player. I could be wrong as I am a newer developer, but, I did look over all the documentation and I didn't see a function that grabs the all time highest rank.

**Comment by CNDRD** [comment]
well okay...

Two issues here:

1) siegeapi (and to my knowledge Ubisoft) does not have a function (or an API endpoint) to get this *all-time highest rank*
If you want to figure out the highest rank you'll have to fetch all the seasons and figure it out yourself (which is kinda stupid since the ranks were changed a lot, new ones, etc.. And the ranking system hasn't stayed the same either. Not really a valid comparison or a information worth having imo..)

2) Since Operation Solar Raid (Y7S4) and the introduction of Ranked 2.0 Ubisoft does NOT store (at least publicly) any meaningful ranked info such as rank or mmr (or max rank and max mmr) for some reason.
If you want data from past Ranked 2.0 seasons go back in time to when that slop was released and start storing them all yourself.

Only way I've found to figure out what was the highest rank bracket for each season for a player is to look at his charms.
However that is very stupid because you need their login info 🧌
