### ISSUE TITLE
Request for Proxy Configuration Support in Network Requests

### ISSUE THREAD

**Issue by BalconyJH** [CNDRD/siegeapi#31]
I hope this issue finds you well.

I would like to request the ability to configure proxy settings for network requests within the library.

I noticed that in https://github.com/CNDRD/siegeapi/blob/e09ded8ddf1754c4937c64fd19982c5c1836ace6/siegeapi/auth.py#L247-L282, it seems possible to pass in proxy parameters. However, in methods like
https://github.com/CNDRD/siegeapi/blob/e09ded8ddf1754c4937c64fd19982c5c1836ace6/siegeapi/auth.py#L76-L110, it appears that this option might not be available.

If there is an existing method to pass proxy parameters that I may have overlooked, I would greatly appreciate any guidance on how to achieve this. I’m raising this issue to seek clarification and potentially suggest an enhancement if needed.

Thank you for your time and assistance!

**Comment by CNDRD** [comment]
🤷
shit was never written to be able to handle anything like this
ill have a look at what can be done, but idk

**Comment by CNDRD** [comment]
aight [v6.3.4](https://github.com/CNDRD/siegeapi/releases/tag/v6.3.4) is released which adds `Auth.extra_get_kwargs`
dictionary that get applied to session kwargs before every get request
this should handle anything and everything one would need to do with the kwargs

not adding any update methods or anything cuz if you need to use a proxy or otherwise meddle with the requests you should know what youre doing :)
